version: '3'
services:
  advertisements:
    container_name: advertisements
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - ads_network
    restart: always

  postgres:
    container_name: postgres
    image: "postgres:9.6.1"
    ports:
      - ${DB_PORT_EXT}:5432
    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "main"
      POSTGRES_DB: "main"
    volumes:
      - ./data_volumes/postgres:/var/lib/postgresql/data
    networks:
      - ads_network
    restart: always

networks:
  ads_network:
